[package]
name = "myfans-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "21.7.0"

[dev-dependencies]
soroban-sdk = { version = "21.7.0", features = ["testutils"] }

[workspace]
members = [
    "contracts/content-access",
    "contracts/content-likes",
    "contracts/creator-deposits",
    "contracts/creator-earnings",
    "contracts/creator-registry",
    "contracts/myfans-lib",
    "contracts/myfans-token",
    "contracts/subscription",
    "contracts/test-consumer",
]

[workspace.dependencies]
soroban-sdk = "21.7.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
